#!/bin/sh

# filter() { mpc | sed "/^volume:/d;s/\\&/&amp;/g;s/\\[paused\\].*/⏸/g;/\\[playing\\].*/d" | paste -sd ' ';}

pidof -x mpdup >/dev/null 2>&1 || mpdup >/dev/null 2>&1 &

case $BUTTON in
	1) cmus-remote -Q ; setsid -f "$TERMINAL" -e ncmpcpp ;;  # right click, pause/unpause
	2) cmus-remote -u ;;  # right click, pause/unpause
	3) cmus-remote -Q ; notify-send "🎵 Music module" "\- Shows mpd song playing.
- ⏸ when paused.
- Left click opens ncmpcpp.
- Middle click pauses.
- Scroll changes track.";;  # right click, pause/unpause
	4) cmus-remote -r ;;  # scroll up, previous
	5) cmus-remote -n;;  # scroll down, next
	6) cmus-remote -Q ; "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
